name: dl_torch
channels: [pytorch, pyg, nvidia, conda-forge]
dependencies:
  - python=3.10
  - matplotlib
  - scikit-learn
  - scipy
  - tqdm
  - nltk
  - ipykernel
  - ipywidgets
  - mlxtend
  - pydotplus
  - shapely
  - ezdxf
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-lightning
  - tensorboard
  - pyg
  - pynvml
  - pip
  - pip:
      - tqdm_joblib